<a href="https://colab.research.google.com/github/maallen3/testing1234/blob/master/has_X_taken_RCR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
import pandas as pd
from datetime import date
import os

In [78]:
outdir="/content/drive/My Drive/RCR/"

In [79]:
todaysdatemonth=date.today().month
todaysdateday=date.today().day
todaysdateyear=date.today().year
today = str(todaysdateyear)+"_"+str(todaysdatemonth)+"_"+str(todaysdateday)

In [80]:
fouryearsago = str(todaysdateyear-4)+"-"+str(todaysdatemonth)+"-"+str(todaysdateday)
fouryearsago

'2020-10-9'

# Who has taken RCR face to face at CU boulder

In [81]:
#this is the google doc i track all the students and emails in
sheet_id = "16w1VKDHkvgt_su6bznwidHjs747sQka35BwcMhwK4cw"
sheet_name1 = "CU_boulder_campus"
sheet_name2 = "other_campus"
sheet_name3= "Currentclass"
sheet_name4= "out_of_date_training"
sheet_name5= "out_of_date_training_other_campus"
cuurl1 = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name1}"
cuurl2 = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name2}"
cuurl3=f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name3}"
cuurl4=f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name4}"
cuurl5=f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name5}"

In [82]:

currentcudf = pd.read_csv(cuurl1)
currentotherdf = pd.read_csv(cuurl2)
takingcudf = pd.read_csv(cuurl3)
oldcudf = pd.read_csv(cuurl4)
oldotherdf = pd.read_csv(cuurl5)

In [94]:
currentcudf

,person,month,year,instructor,Unnamed: 4,Unnamed: 5,Notes,alternative_name,Unnamed: 8
0,Amy Conte,Fall,2020,Aaron Whiteley and Marcelo C. Sousa,NaN,NaN,NaN,NaN,NaN
1,Brianna Fernandez,Fall,2020,Aaron Whiteley and Marcelo C. Sousa,NaN,NaN,NaN,NaN,NaN
2,Danielle Guillen,Fall,2020,Aaron Whiteley and Marcelo C. Sousa,NaN,NaN,NaN,NaN,NaN
3,Julia Roberts,Fall,2020,Aaron Whiteley and Marcelo C. Sousa,NaN,NaN,NaN,NaN,NaN
4,Kristyn Hayashi,Fall,2020,Aaron Whiteley and Marcelo C. Sousa,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
476,Faith Christen,August,2024,Mary Allen,NaN,NaN,undergraduate RCR,NaN,NaN
477,Bart Chen,August,2024,Mary Allen,NaN,NaN,undergraduate RCR,NaN,NaN
478,Lynae Smith,August,2024,Mary Allen,NaN,NaN,undergraduate RCR,NaN,NaN
479,Ethan Johnston,August,2024,Mary Allen,NaN,NaN,undergraduate RCR,NaN,NaN
480,Ruchel Madison,August,2024,Mary Allen,NaN,NaN,undergraduate RCR,NaN,NaN

In [83]:
personeverrcr = pd.concat([currentcudf[["person"]],
                           currentotherdf[["person"]],
                           takingcudf[["person"]],
                           oldcudf[["person"]],
                           oldotherdf[["person"]]])
personeverrcr =personeverrcr.reset_index()
personeverrcr2 = pd.concat([currentcudf[["alternative_name"]],
                           currentotherdf[["alternative_name"]],
                           takingcudf[["alternative_name"]],
                           oldcudf[["alternative_name"]],
                           oldotherdf[["alternative_name"]]])

personeverrcr2 =personeverrcr2.reset_index()
personeverrcr2.columns = ["index", "person"]
personeverrcr = pd.concat([personeverrcr, personeverrcr2])
personeverrcr = personeverrcr.dropna()

In [84]:
personeverrcr

     index                       person
0        0                    Amy Conte
1        1            Brianna Fernandez
2        2             Danielle Guillen
3        3                Julia Roberts
4        4              Kristyn Hayashi
..     ...                          ...
99      99         FREIS,SAMANTHA MARIE
101    101        HORWITZ,TANYA BARBARA
384    384     DOMINIC III,ANTHONY JOHN
391    391        FIORENZA,ALEXANDRIA C
468    468  NEBENFUEHR,BENJAMIN ANDREAS

[1091 rows x 2 columns]

In [85]:
personcurrent = pd.concat([currentcudf[["person"]],
                           currentotherdf[["person"]],
                           takingcudf[["person"]]])
personcurrent =personcurrent.reset_index()
personcurrent2 = pd.concat([currentcudf[["alternative_name"]],
                           currentotherdf[["alternative_name"]],
                           takingcudf[["alternative_name"]]])

personcurrent2 =personcurrent2.reset_index()
personcurrent2.columns = ["index", "person"]
personcurrent = pd.concat([personcurrent, personcurrent2])
personcurrent = personcurrent.dropna()

# Check if someone has taken RCR using CITI

In [86]:
sheet_id2="1iyilsf029gzTBldEXbuSjsutY40-GuKRX9S9OefOeYA"
#this is the google doc i track all the students and emails in
sheet_name1 = "sheet1"
cuurl6 = f"https://docs.google.com/spreadsheets/d/{sheet_id2}/gviz/tq?tqx=out:csv&sheet={sheet_name1}"

In [87]:
citicudf = pd.read_csv(cuurl6)
citicudf

,Last Name,First Name,Date Completed,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,Barba,Magali,1/2/19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deverel-rico,Clarissa,1/2/19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Cho,Kimberly,1/3/19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Hermes,Anna,1/3/19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Mierau,Savannah,1/3/19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3064,Riewe,Eugene,8/3/24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3065,Koger,Kelsey,8/4/24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3066,Davis,Sheila,8/5/24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3067,Thurston,Jeremy,8/5/24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3068,Voida,Amy K.M.,8/7/24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
citicudf["person"] = citicudf["First Name"]+" "+citicudf["Last Name"]
citicudf['Date Completed'] = pd.to_datetime(citicudf['Date Completed'])
citicudf

<ipython-input-88-6105d97e2f5b>:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  citicudf['Date Completed'] = pd.to_datetime(citicudf['Date Completed'])

,Last Name,First Name,Date Completed,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,person
0,Barba,Magali,2019-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Magali Barba
1,Deverel-rico,Clarissa,2019-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clarissa Deverel-rico
2,Cho,Kimberly,2019-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kimberly Cho
3,Hermes,Anna,2019-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Anna Hermes
4,Mierau,Savannah,2019-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Savannah Mierau
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3064,Riewe,Eugene,2024-08-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Eugene Riewe
3065,Koger,Kelsey,2024-08-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kelsey Koger
3066,Davis,Sheila,2024-08-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sheila Davis
3067,Thurston,Jeremy,2024-08-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jeremy Thurston
3068,Voida,Amy K.M.,2024-08-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Amy K.M. Voida

In [89]:
pastciticudf = citicudf.loc[citicudf['Date Completed'] <= fouryearsago]
currentciticudf = citicudf.loc[citicudf['Date Completed'] > fouryearsago]

# Check if someone has taken RCR at CU Boulder

In [90]:
def checkonepersonfortraining(FirstN, LastN, dftocheck):
    dftocheck_person = dftocheck[dftocheck["person"].str.contains(LastN, na=False, case=False)]
    dftocheck_person = dftocheck_person[dftocheck_person["person"].str.contains(FirstN, na=False, case=False)]
    hasalternativenames = len([col for col in dftocheck_person.columns if col.find("alternative_name")>-1])
    if hasalternativenames==1:
        dftocheck_person2 = dftocheck[dftocheck["alternative_name"].str.contains(LastN, na=False, case=False)]
        dftocheck_person2 = dftocheck_person2[dftocheck_person2["alternative_name"].str.contains(FirstN, na=False, case=False)]
        return max(dftocheck_person.shape[0], dftocheck_person2.shape[0])
    else:
        return dftocheck_person.shape[0]

def checkneedtraining(row):
    grant_still_active = row["grant_still_active"]
    faculty = row["faculty"]
    training_inlast4years = row["training_inlast_4years"]
    Program_isSHORT = row["Program_isSHORT"]
    Program_isSummer = row["Program_isSummer"]
    #"Short Courses"
    timetotrain= False
    if grant_still_active:
        if faculty==False:
            if training_inlast4years==False:
                if Program_isSHORT==False:
                    if Program_isSummer==False:
                        timetotrain= True
    return timetotrain

In [60]:
lname="NGUYEN"
fname="TRICIA"
lname="CONTE"
fname="AMY"
checkonepersonfortraining(fname,lname, currentcudf)

1

In [61]:
checkonepersonfortraining(fname,lname, currentciticudf)

0

In [91]:
sheet_id_training="1VqhDRZzJoHtVf-VsQ5pUncgHKRR-eeqzawJqF_98Av4"
sheet_name_training="Sheet1"
trainingurl = f"https://docs.google.com/spreadsheets/d/{sheet_id_training}/gviz/tq?tqx=out:csv&sheet={sheet_name_training}"

trainingdf = pd.read_csv(trainingurl)
trainingdf

,Student Last,Student First,RCR Training,DLA Kick-Off Meeting,Expectations Form,Library Module,Project Summary,"""Presenting"" Seminar",Cluster Sign Up
0,Abdi,Kayo,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alschuler,Jessica,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aronov,Alex,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Belay,Beth,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bender-Stone,Oscar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
81,Wolf,Bella,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,Yates,Andrew,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,Yoder,Eli,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Yunes,Jonah,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,Zhu,Olivia,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [92]:
trainingdf["current_CITI_Training"] = trainingdf.apply(lambda row : checkonepersonfortraining(row['Student First'],row['Student Last'],
                                                                                        currentciticudf), axis = 1)
trainingdf["current_facetoface_Training"] = trainingdf.apply(lambda row : checkonepersonfortraining(row['Student First'],row['Student Last'],
                                                                                        currentcudf), axis = 1)

In [75]:
trainingdf[trainingdf["current_CITI_Training"]>0]

,Student Last,Student First,RCR Training,DLA Kick-Off Meeting,Expectations Form,Library Module,Project Summary,"""Presenting"" Seminar",Cluster Sign Up,current_CITI_Training,current_facetoface_Training
70,Shen,Jasper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0

In [93]:
trainingdf[trainingdf["current_CITI_Training"]>1]

Empty DataFrame
Columns: [Student Last, Student First, RCR Training, DLA Kick-Off Meeting, Expectations Form, Library Module, Project Summary, "Presenting" Seminar, Cluster Sign Up, current_CITI_Training, current_facetoface_Training]
Index: []